In [2]:
import pandas as pd
from pathlib import Path

# Project paths
PROJECT_ROOT = Path("..")
DATA_PATH = PROJECT_ROOT / "data" / "raw" / "DataCoSupplyChainDataset.csv"

# Load raw dataset
df = pd.read_csv(
    DATA_PATH,
    encoding="ISO-8859-1"
)

print("Shape:", df.shape)
df.head()

Shape: (180519, 53)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [3]:
date_columns = [
    "order date (DateOrders)",
    "shipping date (DateOrders)",
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors="coerce")

df[date_columns].dtypes

order date (DateOrders)       datetime64[us]
shipping date (DateOrders)    datetime64[us]
dtype: object

In [4]:
quality_overview = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "missing_count": df.isna().sum(),
    "missing_pct": (df.isna().mean() * 100).round(2),
    "unique_count": df.nunique(dropna=False),
})

quality_overview.sort_values(
    ["missing_pct", "unique_count"],
    ascending=[False, True]
)

,dtype,missing_count,missing_pct,unique_count
Product Description,float64,180519,100.00,1
Order Zipcode,float64,155679,86.24,610
Customer Email,str,0,0.00,1
Customer Password,str,0,0.00,1
Product Status,int64,0,0.00,1
Late_delivery_risk,int64,0,0.00,2
Customer Country,str,0,0.00,2
Customer Segment,str,0,0.00,3
Type,str,0,0.00,4
Days for shipment (scheduled),int64,0,0.00,4
Delivery Status,str,0,0.00,4
Shipping Mode,str,0,0.00,4
Market,str,0,0.00,5
Order Item Quantity,int64,0,0.00,5
Days for shipping (real),int64,0,0.00,7
Order Status,str,0,0.00,9
Department Id,int64,0,0.00,11
Department Name,str,0,0.00,11
Order Item Discount Rate,float64,0,0.00,18
Order Region,str,0,0.00,23
Customer State,str,0,0.00,46
Category Name,str,0,0.00,50
Category Id,int64,0,0.00,51
Product Category Id,int64,0,0.00,51
Order Item Product Price,float64,0,0.00,75
Product Price,float64,0,0.00,75
Order Item Cardprod Id,int64,0,0.00,118
Product Card Id,int64,0,0.00,118
Product Image,str,0,0.00,118
Product Name,str,0,0.00,118
Order Item Profit Ratio,float64,0,0.00,162
Order Country,str,0,0.00,164
Sales,float64,0,0.00,193
Customer City,str,0,0.00,563
Customer Fname,str,0,0.00,782
Customer Zipcode,float64,3,0.00,996
Order Item Discount,float64,0,0.00,1017
Order State,str,0,0.00,1089
Customer Lname,str,8,0.00,1110
Sales per customer,float64,0,0.00,2927
Order Item Total,float64,0,0.00,2927
Order City,str,0,0.00,3597
Longitude,float64,0,0.00,4487
Customer Street,str,0,0.00,7458
Latitude,float64,0,0.00,11250
Customer Id,int64,0,0.00,20652
Order Customer Id,int64,0,0.00,20652
Benefit per order,float64,0,0.00,21998
Order Profit Per Order,float64,0,0.00,21998
shipping date (DateOrders),datetime64[us],0,0.00,63701
order date (DateOrders),datetime64[us],0,0.00,65752
Order Id,int64,0,0.00,65752
Order Item Id,int64,0,0.00,180519

In [5]:
category_mapping = (
    df[["Category Id", "Category Name"]]
    .drop_duplicates()
    .sort_values(["Category Name", "Category Id"])
)

duplicate_category_names = (
    category_mapping
    .groupby("Category Name")
    .filter(lambda x: len(x) > 1)
)

duplicate_category_names

    Category Id Category Name
55           13   Electronics
62           37   Electronics